# -*- coding: utf-8 -*-
"""This module contains the keyword sets for intent detection."""

CODING_KEYWORDS = set(
    map(
        str.lower,
        [
            # Python
            "python",
            "python2",
            "python3",
            "django",
            "flask",
            "fastapi",
            "numpy",
            "pandas",
            "scipy",
            "matplotlib",
            "tensorflow",
            "pytorch",
            "scikit-learn",
            "sklearn",
            "sqlalchemy",
            "asyncio",
            "pip",
            "pip3",
            "conda",
            "poetry",
            "jupyter",
            "virtualenv",
            "pycharm",
            "vs code",
            "vscode",
            "list comprehensions",
            "generators",
            "decorators",
            "gil",
            "type hinting",
            "wsgi",
            "asgi",
            # JavaScript / TS
            "javascript",
            "js",
            "typescript",
            "ts",
            "node.js",
            "nodejs",
            "deno",
            "bun",
            "react",
            "angular",
            "vue",
            "svelte",
            "express",
            "express.js",
            "nestjs",
            "fastify",
            "npm",
            "yarn",
            "pnpm",
            "promises",
            "async/await",
            "closure",
            "closures",
            "this keyword",
            "hoisting",
            "dom",
            "ajax",
            "fetch api",
            "jsx",
            # Ruby
            "ruby",
            "rails",
            "ruby on rails",
            "sinatra",
            "rubygems",
            "gem",
            "blocks",
            "procs",
            "lambdas",
            "mixins",
            # PHP
            "php",
            "laravel",
            "symfony",
            "codeigniter",
            "composer",
            "xdebug",
            "php-fpm",
            # C
            "c",
            "gcc",
            "clang",
            "gdb",
            "make",
            "cmake",
            "pointers",
            "malloc",
            "free",
            "struct",
            "union",
            "preprocessor",
            "posix",
            # C++
            "c++",
            "g++",
            "stl",
            "boost",
            "qt",
            "unreal engine",
            "valgrind",
            "templates",
            "metaprogramming",
            "operator overloading",
            "smart pointers",
            "unique_ptr",
            "shared_ptr",
            "move semantics",
            "lambdas",
            "concurrency",
            "raii",
            # Rust
            "rust",
            "cargo",
            "tokio",
            "actix",
            "rocket",
            "serde",
            "rayon",
            "ownership",
            "borrowing",
            "lifetimes",
            "borrow checker",
            "traits",
            "pattern matching",
            "unsafe",
            "fearless concurrency",
            # Go
            "go",
            "golang",
            "goroutine",
            "goroutines",
            "channels",
            "interfaces",
            "structs",
            "csp",
            "go build",
            "go test",
            "net/http",
            # Java
            "java",
            "jvm",
            "spring",
            "hibernate",
            "jakarta ee",
            "java ee",
            "android sdk",
            "maven",
            "gradle",
            "generics",
            "exceptions",
            "jar",
            "war",
            "java.util.concurrent",
            # Kotlin
            "kotlin",
            "ktor",
            "coroutines",
            "extension functions",
            "data classes",
            "sealed classes",
            "null safety",
            # C#
            "c#",
            ".net",
            "dotnet",
            "asp.net",
            "nuget",
            "xamarin",
            "maui",
            "unity",
            "linq",
            "delegates",
            "events",
            # Swift
            "swift",
            "swiftui",
            "uikit",
            "combine",
            "spm",
            "swift package manager",
            "optionals",
            "arc",
            "protocol oriented",
            # Web
            "html",
            "css",
            "semantic html",
            "dom",
            "canvas",
            "svg",
            "forms",
            "selectors",
            "specificity",
            "box model",
            "flexbox",
            "grid",
            "media queries",
            "responsive",
            "variables",
            "custom properties",
            "transitions",
            "animations",
            "sass",
            "less",
            "postcss",
            "tailwind",
            "bootstrap",
            # SQL / DB
            "sql",
            "postgresql",
            "mysql",
            "sqlite",
            "tsql",
            "pl/sql",
            "ddl",
            "dml",
            "dcl",
            "select",
            "insert",
            "update",
            "delete",
            "join",
            "joins",
            "transactions",
            "acid",
            "indexes",
            "stored procedures",
            "normalization",
            # Dev
            "api",
            "regex",
            "shell",
            "bash",
            "docker",
            "kubernetes",
            "git",
            "github",
            "termux",
            "cli",
            "build",
            "compile",
            "script",
            "debug",
            "stack trace",
            "unit test",
            "benchmark",
            "profiling",
            "linter",
            "formatter",
            # Shell/CLI (added)
            "shell",
            "sh",
            "bash",
            "zsh",
            "fish",
            "csh",
            "tcsh",
            "ksh",
            "command-line interface",
            "cli",
            "shell scripting",
            "interpreter",
            "terminal",
            "console",
            "ls",
            "cd",
            "pwd",
            "cp",
            "mv",
            "rm",
            "mkdir",
            "touch",
            "cat",
            "echo",
            "grep",
            "sed",
            "awk",
            "find",
            "xargs",
            "chmod",
            "chown",
            "stdin",
            "stdout",
            "stderr",
            "pipe",
            "pipes",
            "<",
            ">",
            "2>",
            "|",
            "environment variables",
            "$home",
            "$path",
            "local variables",
            "parameter expansion",
            "${",
            "shebang",
            "#/bin/bash",
            "conditional statements",
            "if",
            "then",
            "else",
            "elif",
            "fi",
            "case",
            "loops",
            "for",
            "while",
            "until",
            "functions",
            "exit codes",
            "success 0",
            "non-zero",
            "$?",
            "single quotes",
            "double quotes",
            "backticks",
            "command substitution",
            "$()",
            "foreground",
            "background",
            "jobs",
            "fg",
            "bg",
            "ctrl+z",
            "ctrl+c",
            "read write execute",
            "user group other",
            "rwx",
            "shellshock",
            "globbing",
            "wildcards",
            "*",
            "?",
            "[]",
            "regular expressions",
            "process substitution",
            "<(",
            "here document",
            "heredoc",
            "<<",
            "set -e",
            "set -u",
            "set -x",
            "set -o pipefail",
            "curl",
            "wget",
            "ssh",
            "scp",
            "top",
            "ps",
            "kill",
            "tar",
            "gzip",
            "man",
            "sudo",
        ],
    )
)

GENERAL_KEYWORDS = set(
    map(
        str.lower,
        [
            "explain",
            "summarize",
            "story",
            "poem",
            "email",
            "letter",
            "outline",
            "notes",
            "idea",
            "brainstorm",
            "teach",
            "define",
            "translate",
            "rephrase",
            "list",
            "compare",
            "contrast",
            "analyze",
            "speech",
            "copywriting",
            "marketing",
        ],
    )
)
